# Config file for automatic testing at travis-ci.org

language: python
python: 3.6

dist: trusty

branches:
  only:
    - master

services:
  - postgresql

matrix:
  include:
    - env: TOX_ENV=py35-django110-es60 ES_APT_URL=https://artifacts.elastic.co/packages/6.x/apt
      python: 3.5
    - env: TOX_ENV=py35-django111-es60 ES_APT_URL=https://artifacts.elastic.co/packages/6.x/apt
      python: 3.5
    - env: TOX_ENV=py35-django20-es60 ES_APT_URL=https://artifacts.elastic.co/packages/6.x/apt
      python: 3.5
    - env: TOX_ENV=py35-django21-es60 ES_APT_URL=https://artifacts.elastic.co/packages/6.x/apt
      python: 3.5

before_install:
  - pip install --upgrade pip
  # work around https://github.com/travis-ci/travis-ci/issues/8363
  - wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  - echo "deb $ES_APT_URL stable main" | sudo tee -a /etc/apt/sources.list.d/elk.list
  - sudo apt-get update && sudo apt-get install elasticsearch -y
  - sudo service elasticsearch start

install: pip install -r requirements/travis.txt

before_script:
  - psql -c "CREATE DATABASE postgres;" -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'postgres';" -U postgres
  # sleep for elasticsearch
  - sleep 10

# command to run tests
script: tox -e $TOX_ENV

after_success:
  - codecov -e $TOX_ENV